spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true
    database: mysql
  profiles:
    include:
      - aws
      - credentials

  security:
    jwt:
      header: Authorization
      secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWppd29vbi1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3QtdHV0b3JpYWwK
      token-validity-in-seconds: 86400


logging:
  level:
    org.hibernate.SQL: debug
