name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Create application-aws.yml and application-credentials.yml
        run: |
          mkdir -p ./src/main/resources
          echo "${{ secrets.AWS_CONFIGURATION }}" | base64 --decode > ./src/main/resources/application-aws.yml
          echo "${{ secrets.CREDENTIALS_CONFIGURATION }}" | base64 --decode > ./src/main/resources/application-credentials.yml
          
        shell: bash

      - name: Build with Gradle
        run: ./gradlew bootJar

      - name: Docker login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Spring Boot Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/boomarble:latest -f Dockerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}/boomarble:latest

      - name: Build and push Nginx Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/nginx:latest -f ./nginx/Dockerfile ./nginx
          docker push ${{ secrets.DOCKER_USERNAME }}/nginx:latest

      - name: Executing remote SSH commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            sudo /usr/local/bin/docker-compose down
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/boomarble:latest
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/nginx:latest
            sudo /usr/local/bin/docker-compose up -d
            sudo docker image prune -f